name: 'app'
type: 'python:3.8'
dependencies:
    python3:
       pipenv: '2018.10.13'
relationships:
    database: "database:postgresql"
web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET myapp.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true
disk: 512
mounts:
    'logs':
        source: local
        source_path: logs
hooks:
  build: |
    pipenv install --system --deploy

    mkdir logs
    python manage.py collectstatic
    rm -rf logs
  deploy: |
    python manage.py migrate
